package cn.wsg.commons.system.cmd.ffmpeg;

import cn.wsg.commons.lang.jackson.JsonDurationFormat;
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Duration;
import java.time.LocalDateTime;
import lombok.Getter;

/**
 * The information about the container format of the input multimedia stream.
 *
 * @author Kingen
 */
@Getter
public class Format {

    @JsonProperty(value = "filename", required = true)
    private String filename;

    @JsonProperty(value = "format_name", required = true)
    private String formatName;

    @JsonProperty(value = "format_long_name", required = true)
    private String formatLongName;

    @JsonProperty(value = "size", required = true)
    private long size;

    @JsonProperty(value = "bit_rate", required = true)
    private long bitRate;

    @JsonProperty(value = "duration", required = true)
    @JsonDurationFormat(format = JsonDurationFormat.Format.DOUBLE)
    private Duration duration;

    @JsonProperty(value = "start_time", required = true)
    private double startTime;

    @JsonProperty(value = "probe_score", required = true)
    private int probeScore;

    @JsonProperty(value = "nb_programs", required = true)
    private int nbPrograms;

    @JsonProperty(value = "nb_streams", required = true)
    private int nbStreams;

    @JsonProperty("tags")
    private FormatTags tags;

    Format() {
    }

    @Getter
    public static class FormatTags {

        @JsonProperty("title")
        private String title;

        @JsonProperty("encoder")
        @JsonAlias("ENCODER")
        private String encoder;

        @JsonProperty("creation_time")
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'", timezone = "utc")
        private LocalDateTime creationTime;

        @JsonProperty("Creation Date")
        @JsonFormat(pattern = "M/d/yyyy H:mm:ss")
        private LocalDateTime creationDate;

        @JsonProperty("author")
        private String author;

        @JsonProperty("Generated By")
        private String generatedBy;

        @JsonProperty("Encoded/Released by")
        private String releasedBy;

        @JsonProperty("major_brand")
        private String majorBrand;

        @JsonProperty("minor_version")
        private Integer minorVersion;

        @JsonProperty("compatible_brands")
        private String compatibleBrands;

        @JsonProperty("copyright")
        private String copyright;

        @JsonProperty("comment")
        private String comment;

        @JsonProperty("ASMRuleBook")
        private String asmRuleBook;

        @JsonProperty("Audiences")
        private String audiences;

        @JsonProperty("audioMode")
        private String audioMode;

        @JsonProperty("Description")
        @JsonAlias("description")
        private String description;

        @JsonProperty("Email")
        private String email;

        @JsonProperty("HomeWeb")
        private String website;

        @JsonProperty("Keywords")
        private String keywords;

        @JsonProperty("Modification Date")
        @JsonFormat(pattern = "M/d/yyyy H:mm:ss")
        private LocalDateTime modificationDate;

        @JsonProperty("videoMode")
        private String videoMode;

        @JsonProperty("software")
        private String software;

        @JsonProperty("File ID")
        private String fileId;

        FormatTags() {
        }
    }
}